# automation:

- alias: Radio volume
  trigger:
    platform: state
    entity_id: input_number.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.afspeelmedium", "Woonkamer") %} media_player.woonkamer
        {% elif is_state("input_select.afspeelmedium", "Slaapkamer") %} media_player.slaapkamer
        {% elif is_state("input_select.afspeelmedium", "Chromecast Woonkamer") %} media_player.chromecast_woonkamer
        {% elif is_state("input_select.afspeelmedium", "Chromecast Slaapkamer") %} media_player.chromecast_slaapkamer
        {% elif is_state("input_select.afspeelmedium", "Nest") %} media_player.nest
        {% endif %}
      volume_level: '{{  states.input_number.volume_radio.state  }}' 

- alias: Afval
  trigger:
    platform: time
    at: "18:00:00"
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: "{% if is_state('sensor.afvalinfo_tomorrow', 'gft') %}true{% endif %}"
    - condition: template
      value_template: "{% if is_state('sensor.afvalinfo_tomorrow', 'papier') %}true{% endif %}"
    - condition: template
      value_template: "{% if is_state('sensor.afvalinfo_tomorrow', 'restafval') %}true{% endif %}"
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: Morgen wordt {{states.sensor.afvalinfo_tomorrow.state}} opgehaald!
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: Morgen wordt {{states.sensor.afvalinfo_tomorrow.state}} opgehaald!
  - service: notify.mobile_app_iphone_van_susan
    data:
      message: Morgen wordt {{states.sensor.afvalinfo_tomorrow.state}} opgehaald!

- alias: Update status wasmachine - draait
  trigger:
  - platform: numeric_state
    entity_id: sensor.wasmachine_watts
    above: '5'
    for:
      minutes: 10
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: "Draait"

- alias: Update status wasmachine - klaar
  trigger:
  - platform: numeric_state
    entity_id: sensor.wasmachine_watts
    below: '10'
    for:
      minutes: 10
  condition:
  - condition: state
    entity_id: input_select.wasmachine_status
    state: "Draait"
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: "Klaar"

- alias: Notify - Wasmachine klaar
  trigger:
  - platform: state
    entity_id: input_select.wasmachine_status
    to: "Klaar"
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: De wasmachine is klaar
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: De wasmachine is klaar
  - service: notify.mobile_app_iphone_van_susan
    data:
      message: De wasmachine is klaar
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.woonkamer
      volume_level: 0.8
  - delay:
      seconds: 2
  - service: tts.google_translate_say
    entity_id: media_player.woonkamer
    data_template:
      message: 'De wasmachine is klaar'
      language: 'nl'
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: "Uit"

- alias: Vakantiemodus
  trigger:
  - platform: sun
    event: sunset
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.susan_ter_laak
      state: not_home
    - condition: state
      entity_id: person.ronan_berendsen
      state: not_home
    - condition: state
      entity_id: input_boolean.holidaymode
      state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.woonkamer
    data:
      brightness_pct: 80
  - delay:
      hours: 3
  - service: light.turn_off
    entity_id: light.woonkamer

- alias: Welterusten
  trigger:
    platform: state
    entity_id: input_boolean.welterusten
    to: 'on'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.woonkamer
      volume_level: 0.8
  - delay:
      seconds: 2
  - service: tts.google_translate_say
    entity_id: media_player.woonkamer
    data_template:
      message: 'Welterusten!'
      language: 'nl'
  - service: light.turn_on
    entity_id: light.slaapkamerlamp
    data:
      brightness_pct: 80
  - delay:
      seconds: 5
  - service: light.turn_off
    entity_id: light.slaapkamerlamp
    data:
      transition: 600
  - delay:
      seconds: 10
  - service: light.turn_off
    entity_id: light.beneden
  - service: input_boolean.turn_off
    entity_id: input_boolean.welterusten

- alias: Lampen aan als Susan of Ronan thuis komt
  trigger:
  - platform: template
    value_template: "{% if is_state('person.susan_ter_laak', 'home') %}true{% endif %} "
  - platform: template
    value_template: "{% if is_state('person.ronan_berendsen', 'home') %}true{% endif %} "
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: template
      value_template: "{{ states('light.woonkamer') == 'off' }}"
    - condition: template
      value_template: "{{ states('light.tuinlampen') == 'off' }}"
    - condition: or
      conditions:
      - condition: state
        entity_id: person.susan_ter_laak
        state: home
      - condition: state
        entity_id: person.ronan_berendsen
        state: home
  action:
  - service: light.turn_on
    entity_id: light.woonkamer
    data:
      brightness_pct: 80
  - service: light.turn_on
    entity_id: light.tuinlampen
    
- alias: Lampen aan als het donker wordt en Susan of Ronan is thuis
  trigger:
  - platform: sun
    event: sunset
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: person.susan_ter_laak
      state: home
    - condition: state
      entity_id: person.ronan_berendsen
      state: home
  action:
  - service: light.turn_on
    entity_id: light.woonkamer
    data:
      brightness_pct: 80
  - service: light.turn_on
    entity_id: light.tuinlampen

- alias: Melding indien Susan thuis komt
  trigger:
    platform: state
    entity_id: person.susan_ter_laak
    to: home
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: Susan is thuis
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: Susan is thuis

- alias: Melding indien Susan het huis verlaat
  trigger:
    platform: state
    entity_id: person.susan_ter_laak
    from: home
    to: not_home
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: Susan verlaat het huis
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: Susan verlaat het huis

- alias: Tado check - bij verlaten huis
  trigger:
  - platform: state
    entity_id: person.susan_ter_laak
    from: home
    to: not_home
  - platform: state
    entity_id: person.ronan_berendsen
    from: home
    to: not_home
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ not is_state('person.susan_ter_laak', 'home') }}"
    - condition: template
      value_template: "{{ not is_state('person.ronan_berendsen', 'home') }}"
    - condition: state
      entity_id: sensor.woonkamer_tado_mode
      state: 'HOME'
    - condition: template
      value_template: "{{ states('sensor.woonkamer_heating') | int != 0 }}"
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: Er is niemand meer thuis, maar Tado staat nog steeds aan
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: Er is niemand meer thuis, maar Tado staat nog steeds aan

- alias: Tado check - bij aanslaan tijdens afwezigheid
  trigger:
  - platform: template
    value_template: "{% if is_state('sensor.woonkamer_heating', '0.0') %}false{% endif %}"
  condition:
    condition: and
    conditions:
    - condition: template
      value_template: "{{ not is_state('person.susan_ter_laak', 'home') }}"
    - condition: template
      value_template: "{{ not is_state('person.ronan_berendsen', 'home') }}"
#    - condition: state
#      entity_id: sensor.woonkamer_tado_mode
#      state: 'HOME'
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: Tado slaat zojuist aan terwijl er niemand thuis is
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: Tado slaat zojuist aan terwijl er niemand thuis is

- alias: Melding indien Tado handmatig wordt aangepast
  trigger:
    platform: state
    entity_id: sensor.woonkamer_overlay
    to: 'True'
  action:
  - service: notify.mobile_app_sm_g930f
    data:
      message: De verwarming is zojuist handmatig ingesteld op {{state_attr('sensor.woonkamer_temperature', 'setting')}} {{state_attr('sensor.woonkamer_temperature', 'unit_of_measurement')}}
  - service: notify.mobile_app_iphone_van_ronan
    data:
      message: De verwarming is zojuist handmatig ingesteld op {{state_attr('sensor.woonkamer_temperature', 'setting')}} {{state_attr('sensor.woonkamer_temperature', 'unit_of_measurement')}}


#- alias: Update reistijd
#  initial_state: 'on'
#  trigger:
#    - platform: time_pattern
#      minutes: '/5'
#  condition:
#    - condition: time
#      after: '06:00:00'
#      before: '09:00:00'
#    - condition: time
#      weekday:
#        - mon
#        - tue
#        - wed
#        - thu
#        - fri
#  action:
#    - service: homeassistant.update_entity
#      entity_id: sensor.reistijd